//Create a server
//1. Import http module, 2.Create a server with the imported http module bu passing a function, which takes request and response as parameters
//A request is generated by node js for us and a response is what we would like to send back to client

const http = require('http');
const m2ref = require('./routes')
http.createServer(m2ref).listen(3050);